# Generated by Django 6.0.6 on 2026-06-03 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('logo_url', models.URLField(blank=True)),
                ('primary_color', models.CharField(default='#2563eb', max_length=20)),
                ('tour_url', models.URLField(blank=True, help_text='URL of the 3DVista virtual tour, loaded in an iframe.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TourResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=200)),
                ('score', models.IntegerField(default=0)),
                ('total_score', models.IntegerField(default=0)),
                ('answered_questions', models.IntegerField(default=0)),
                ('total_questions', models.IntegerField(default=0)),
                ('items_found', models.IntegerField(default=0)),
                ('total_items', models.IntegerField(default=0)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='api.client')),
            ],
            options={
                'ordering': ['-completed_at'],
            },
        ),
    ]
